---
   - name: 'Add ppa'
     sudo: yes
     apt_repository:
      repo: "ppa:vbernat/haproxy-1.5"
      state: present
      update_cache: yes

   - name: 'Install'
     apt:
       pkg: haproxy
       state: latest

   - name: 'Enable'
     service:
       name: haproxy
       enabled: yes

   - name: 'Use cfg file'
     template: src=templates/haproxy.cfg
           dest=/etc/haproxy/haproxy.cfg
           backup=yes
     notify:
       - restart
